spring:
  application:
    name: yuapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.84.87:3306/huiapi
    username: guqin
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        same-site: none
        secure: true
#  ssl:
#    key-store: classpath:full_chain.pem
#    key-store-type: PKCS12
#    key-store-password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
huiapi:
  client:
    access-key: huiapi
    secret-key: abcdefg
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://38.181.158.67:8848 #nacos://38.181.158.67:8848
    simplified: true
  metadata-report:
    address: nacos://38.181.158.67:8848

